### ISSUE TITLE
Not working with flutter 3.0

### ISSUE THREAD

**Issue by tasaddaq-hussain** [wilburt/flutter_paystack#125]
error:
* What went wrong:
Execution failed for task ':flutter_paystack:compileDebugKotlin'.
> Compilation error. See log for more details

**Comment by Dr-Usman** [comment]
[Solution](https://github.com/wilburt/flutter_paystack/issues/120#issuecomment-1143474567)

**Comment by ndesamuelmbah** [comment]
+1 to @fredEbho, we absolutely need Flutter 3.X support.

**Comment by wilburt** [comment]
This has been fixed in 1.0.6. Can you update the package verison?
